export default {
    isShowStrikethrough:false,
    globalConversionSetting:'every',
    pageName: 'Checkout Page 1',
    templateType: 'RightSidebar',
    themeType: 'Classic',
    summaryPlacement:'Before Buy Button',
    backgroundColor: '#F6F8FC',
    titleForm: 'Data Penerima:',
    titleVariations: 'Pilihan Produk:',
    titlePayment: 'Metode Pembayaran:',
    titleBullet: 'Yang Anda Dapatkan:',
    titleShipping: 'Pengiriman:',
    headerImage: '',
    showTitle: false,
    showTagline: false,
    title: '',
    tagline: '',
    showProductImages: true,
    showRatingItemSold: false,
    showTestimonials: false,
    showOrderReview: true,
    showCreateOrder: true,
    showContentBullet: true,
    showSeals: true,
    showVideo: false,
    componentVideo: '',
    sealText: ['100Jaminan', 'Enkripsi'],
    variationSelectType: 'Modern',
    isLabel: 'hideLabel',
    formMode: 'Show All',
    initialFields: '',
    isSaveInfoNextTime: false,
    addShipping: false,
    showBumpProduct: false,
    showBumpProductStep1: false,
    buyButtonChild: {},
    dropship: false,
    coupon: false,
    boldBuyButtonText: false,
    isAddIcon: false ,
    floatingButton: false,
    selectedIconName: 'chevron-right',
    selectedSplit: 'regular',
    buyButtonFontSize: "Medium",
    buyButtonText: 'Beli Sekarang',
    buyButtonStyle: '#04ac0d',
}