export default {
    enableProductOptions: false,
    name: '',
    url: '',
    images: [],
    category: 'Tanpa Kategori',
    category2: '',
    category3: '',
    status: 'active',
    price: '0',
    priceCompare: "0",
    costPerItem: '0',
    enableSplitPrice: false,
    splitPriceData: [
    ],
    whosale: false,
    whosaleData: [
        { count: '', price: '' },
    ],
    type: 'simple',
    formOption: 'single',
    multiplyVariations: false,
    cartOrder: false,
    addQuantity: false,
    SKU: '',
    barcode: '',
    trackQuantity: false,
    continueSelling: true,
    available: '',
    stockStatus: 'In Stock',
    weight: 1000,
    addShipping: false,
    shippingType: 'automated',
    shipFrom: '',
    additionalCost: '',
    flatShippingPrice: '',
}